# curl --location --request POST 'https://gb-backend1-reguser.herokuapp.com/create'
#--header 'Content-MD5: application/json'
#--header 'Authorization: Basic YWRtaW46YWRtaW4='
#--header 'Content-Type: application/json'
#--data-raw '{"name":"userpuser"}'
POST https://gb-backend1-reguser.herokuapp.com/create
Content-MD5: application/json
Authorization: Basic YWRtaW46YWRtaW4=
Content-Type: application/json

{"name":"userpuser322"}

###

# curl --location --request GET 'https://gb-backend1-reguser.herokuapp.com/search/us'
#--header 'Content-MD5: application/json'
#--header 'Authorization: Basic YWRtaW46YWRtaW4='
#--data-raw ''
GET https://gb-backend1-reguser.herokuapp.com/search/us
Content-MD5: application/json
Authorization: Basic YWRtaW46YWRtaW4=
Content-Type: application/x-www-form-urlencoded

###

